Azure_Assignment/Models/Exportation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exportation
    {
        public int ExportationID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
    }
}

Azure_Assignment/Areas/Admin/Controllers/ExportationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Azure_Assignment.EF;

namespace Azure_Assignment.Areas.Admin.Controllers
{
    [Authorize(Roles = "0,1")]
    public class ExportationsController : BaseController
    {
        private DataPalkia db = new DataPalkia();

        
        public ActionResult Index()
        {
            var exportation = db.Exportation.Include(e => e.Products).Include(e => e.Users);
            ViewBag.ProductList = new List<Products>(db.Products.Include(i => i.ProductImage).ToList());
            return View(exportation.ToList());
        }

        
        public ActionResult Create(int? id)
        {
            var product = db.Products.FirstOrDefault(p => p.ProductID == id);
            ViewBag.Product = product;
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Export([Bind(Include = "ExportationID,ProductID,Username,ExportDate,UnitPrice,Quantity")] Exportation exportation)
        {
            if (ModelState.IsValid)
            {
                var product = db.Products.Single(p => p.ProductID == exportation.ProductID);
                if (exportation.Quantity > product.UnitsInStock)
                {
                    TempData["Error"] = "Quantity must be less than unit in stock";
                    return RedirectToAction("Create", new { id = product.ProductID });
                }
                else
                {
                    product.UnitsInStock -= exportation.Quantity;
                    db.Exportation.Add(exportation);
                    db.SaveChanges();
                    TempData["Notice_Save_Success"] = true;

                    return RedirectToAction("Index");
                }
                
            }

            return RedirectToAction("Create", new { id = exportation.ProductID });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Azure_Assignment/Areas/Admin/Views/Exportations/Create.cshtml
@model Azure_Assignment.EF.Exportation

@{
    ViewBag.Title = "Create";
    var user = (Azure_Assignment.Areas.Admin.Models.UserLogin)Session["USER_SESSION"];
}
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Export out of Stock</h1>
                    <h5 style="color:red">@TempData["Error"]</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                        <li class="breadcrumb-item"><a href="~/Admin/Exportations/">Exportations</a></li>
                        <li class="breadcrumb-item active">Export out of Stock</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="card card-green">
                        <div class="card-header">
                            <h3 class="card-title">Export out of Stock</h3>
                        </div>
                        @using (Html.BeginForm("Export", "Exportations", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-horizontal">
                                <div class="card-body">
                                    <div class="form-group row">
                                        <label class="control-label col-md-2">Product Name</label>
                                        <div class="col-md-10">
                                            <input type="hidden" name="ProductID" value="@ViewBag.Product.ProductID">
                                            <input type="text" name="ProductName" value="@ViewBag.Product.ProductName" class="form-control" readonly>
                                            @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.Username, "Username", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            <input type="text" name="Username" value="@user.Username" class="form-control" readonly>
                                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.ExportDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.ExportDate, new { htmlAttributes = new { @class = "form-control oso", @type = "datetime-local", @required = "required" } })
                                            @Html.ValidationMessageFor(model => model.ExportDate, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control", @required = "required", @type = "number", @min = 1 } })
                                            @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", @required = "required", @type = "number", @min = 1 } })
                                            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-success">Export</button>
                                    <a class="btn btn-default float-right" href="@Url.Action("Index", "Exportations")">Cancel</a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>