Azure_Assignment/ViewModels/BlogCategoriesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Azure_Assignment.ViewModels
{
    public class BlogCategoriesViewModel
    {
        public int BlogCategoryID { get; set; }
        public string BlogCategoryName { get; set; }
    }
}

Azure_Assignment/Areas/Admin/Controllers/BlogCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Azure_Assignment.EF;

namespace Azure_Assignment.Areas.Admin.Controllers
{
    [Authorize(Roles = "0,1")]
    public class BlogCategoriesController : BaseController
    {
        private DataPalkia db = new DataPalkia();

        public ActionResult Index()
        {
            return View(db.BlogCategories.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogCategories blogCategories = db.BlogCategories.Find(id);
            if (blogCategories == null)
            {
                return HttpNotFound();
            }
            return View(blogCategories);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BlogCategoryID,BlogCategoryName")] BlogCategories blogCategories)
        {
            if (ModelState.IsValid)
            {
                db.BlogCategories.Add(blogCategories);
                db.SaveChanges();
                TempData["Notice_Create_Success"] = true;
                return RedirectToAction("Index");
            }

            return View(blogCategories);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogCategories blogCategories = db.BlogCategories.Find(id);
            if (blogCategories == null)
            {
                return HttpNotFound();
            }
            return View(blogCategories);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BlogCategoryID,BlogCategoryName")] BlogCategories blogCategories)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blogCategories).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Notice_Save_Success"] = true;
                return RedirectToAction("Index");
            }
            return View(blogCategories);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogCategories blogCategories = db.BlogCategories.Find(id);
            if (blogCategories == null)
            {
                return HttpNotFound();
            }
            return View(blogCategories);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                BlogCategories blogCategories = db.BlogCategories.Find(id);
                db.BlogCategories.Remove(blogCategories);
                db.SaveChanges();
                TempData["Notice_Delete_Success"] = true;
            }
            catch (Exception)
            {
                TempData["Notice_Delete_Fail"] = true;
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Azure_Assignment/Areas/Admin/Views/BlogCategories/Create.cshtml
@model Azure_Assignment.EF.BlogCategories


<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Create Blog Category</h1>
                    <h5 style="color:red">@ViewBag.Error</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                        <li class="breadcrumb-item"><a href="~/Admin/BlogCategories/">Blog Categories</a></li>
                        <li class="breadcrumb-item active">Create Blog Category</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="card card-green">
                        <div class="card-header">
                            <h3 class="card-title">New Blog Category</h3>
                        </div>
                        @using (Html.BeginForm("Create", "BlogCategories", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-horizontal">
                                <div class="card-body">
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.BlogCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.BlogCategoryName, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.BlogCategoryName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-success">Create</button>
                                    <button type="reset" class="btn btn-default float-right" onclick="window.location = './'">Cancel</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Azure_Assignment/Areas/Admin/Views/BlogCategories/Delete.cshtml
@model Azure_Assignment.EF.BlogCategories

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Delete Blog Category</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                        <li class="breadcrumb-item"><a href="~/Admin/BlogCategories/">Blog Categories</a></li>
                        <li class="breadcrumb-item active">Delete</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-8">
                        <h1 style="font-weight:bold; font-size:25px" class="card-title">Are you sure you want to delete this?</h1>
                    </div>

                    <div class="col-sm-2">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <div class="card-tools">
                                    <input type="submit" value="Delete" class="btn btn-block btn-secondary float-right btn-danger" />
                                </div>
                            </div>
                        }
                    </div>

                    <div class="card-tools col-sm-2">
                        <button class="btn btn-block btn-secondary float-right" onclick="window.location.href = '../'">Cancel</button>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-12 order-12 order-md-12">
                        <div class="row">
                            <div class="col-12">
                                <div class="post">
                                    <div class="col-sm-2 user-block">
                                        <strong>@Html.DisplayNameFor(model => model.BlogCategoryID)</strong>:
                                    </div>
                                    <p class="col-sm-10">
                                        @Html.DisplayFor(model => model.BlogCategoryID)
                                    </p>
                                </div>

                                <div class="post">
                                    <div class="col-sm-2 user-block">
                                        <strong>@Html.DisplayNameFor(model => model.BlogCategoryName)</strong>:
                                    </div>
                                    <p class="col-sm-10">
                                        @Html.DisplayFor(model => model.BlogCategoryName)
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
</div>

Azure_Assignment/Areas/Admin/Views/BlogCategories/Details.cshtml
@model Azure_Assignment.EF.BlogCategories

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Blog Category Detail</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                        <li class="breadcrumb-item"><a href="~/Admin/BlogCategories/">Blog Categories</a></li>
                        <li class="breadcrumb-item active">Detail</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="card">
            <div class="card-header">
                <h1 style="font-weight:bold; font-size:25px;" class="card-title">Detail of Blog Category</h1>

                <div class="card-tools">
                    <button class="btn btn-block btn-secondary float-right" onclick="window.location.href = '../'">Back to List</button>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-12 order-12 order-md-12">
                        <div class="row">
                            <div class="col-12">
                                <div class="post">
                                    <div class="col-sm-2 user-block">
                                        <strong>@Html.DisplayNameFor(model => model.BlogCategoryID)</strong>:
                                    </div>
                                    <p class="col-sm-10">
                                        @Html.DisplayFor(model => model.BlogCategoryID)
                                    </p>
                                </div>

                                <div class="post">
                                    <div class="col-sm-2 user-block">
                                        <strong>@Html.DisplayNameFor(model => model.BlogCategoryName)</strong>:
                                    </div>
                                    <p class="col-sm-10">
                                        @Html.DisplayFor(model => model.BlogCategoryName)
                                    </p>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
</div>

<style>
    #imageDetail {
        display: block;
        width: 100%;
        height: auto;
    }
</style>

Azure_Assignment/Areas/Admin/Views/BlogCategories/Edit.cshtml
@model Azure_Assignment.EF.BlogCategories

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Blog Category</h1>
                    <h5 style="color:red">@ViewBag.Error</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                        <li class="breadcrumb-item"><a href="~/Admin/BlogCategories/">Blog Categories</a></li>
                        <li class="breadcrumb-item active">Edit Blog Category</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Edit Blog Category</h3>
                        </div>
                        @using (Html.BeginForm("Edit", "BlogCategories", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.BlogCategoryID)
                                <div class="card-body">
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.BlogCategoryName, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                                        <div class="col-sm-10">
                                            @Html.EditorFor(model => model.BlogCategoryName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter name of product category" } })
                                            @Html.ValidationMessageFor(model => model.BlogCategoryName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-success">Save</button>
                                    <button type="reset" class="btn btn-default float-right" onclick="window.location = '../'">Cancel</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Azure_Assignment/Areas/Admin/Views/BlogCategories/Index.cshtml
@model IEnumerable<Azure_Assignment.EF.BlogCategories>

<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Manage Blog Categories</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                        <li class="breadcrumb-item active">Blog Categories</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Data of Blog Categories</h3>
                    <p>
                        <a class="btn btn-success btn-sm float-right" href="~/Admin/BlogCategories/Create">
                            <i class="fas fa-plus">
                            </i>
                            Create New
                        </a>
                        <a style="cursor:pointer; color:white" id="print" class="btn btn-primary btn-sm float-right"><i class="fas fa-print"></i> Print</a>
                    </p>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="tbl_BlogCategories" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.BlogCategoryName)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.BlogCategoryName)
                                    </td>
                                    <td class="project-actions text-right">
                                        <a class="btn btn-primary btn-sm" href="~/Admin/BlogCategories/Details/@item.BlogCategoryID">
                                            <i class="fas fa-folder">
                                            </i>
                                            View
                                        </a>
                                        <a class="btn btn-info btn-sm" href="~/Admin/BlogCategories/Edit/@item.BlogCategoryID">
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Edit
                                        </a>
                                        <a class="btn btn-danger btn-sm" href="~/Admin/BlogCategories/Delete/@item.BlogCategoryID">
                                            <i class="fas fa-trash">
                                            </i>
                                            Delete
                                        </a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</div>
@section ScriptConfig
{
    <link href="~/Scripts/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Scripts/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" rel="stylesheet" />
    <script src="~/Scripts/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Scripts/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script>
        $("#tbl_BlogCategories").DataTable({
            "responsive": true,
            "autoWidth": false,
            "aoColumns": [
                null,
                { sWidth: '180px' }
            ]
        });

        $('#print').click(function () {
            window.print();
            return false;
        });
        
    </script>
}