Azure_Assignment/Models/Payment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int PaymentID { get; set; }
        public string PaymentName { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}

Azure_Assignment/Models/Payments.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payments()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int PaymentID { get; set; }
        public string PaymentName { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}

Azure_Assignment/Areas/Admin/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Azure_Assignment.EF;
using Rotativa;

namespace Azure_Assignment.Areas.Admin.Controllers
{
    [Authorize(Roles = "0")]
    public class PaymentsController : BaseController
    {
        private DataPalkia db = new DataPalkia();

        // GET: Admin/Payments
        public ActionResult Index()
        {
            return View(db.Payments.ToList());
        }

        // GET: Admin/Payments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payments payments = db.Payments.Find(id);
            if (payments == null)
            {
                return HttpNotFound();
            }
            return View(payments);
        }

        // GET: Admin/Payments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Payments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PaymentID,PaymentName")] Payments payments)
        {
            if (ModelState.IsValid)
            {
                db.Payments.Add(payments);
                db.SaveChanges();
                TempData["Notice_Create_Success"] = true;
                return RedirectToAction("Index");
            }

            return View(payments);
        }

        // GET: Admin/Payments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payments payments = db.Payments.Find(id);
            if (payments == null)
            {
                return HttpNotFound();
            }
            return View(payments);
        }

        // POST: Admin/Payments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PaymentID,PaymentName")] Payments payments)
        {
            if (ModelState.IsValid)
            {
                db.Entry(payments).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Notice_Save_Success"] = true;
                return RedirectToAction("Index");
            }
            return View(payments);
        }

        // GET: Admin/Payments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payments payments = db.Payments.Find(id);
            if (payments == null)
            {
                return HttpNotFound();
            }
            return View(payments);
        }

        // POST: Admin/Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Payments payments = db.Payments.Find(id);
                db.Payments.Remove(payments);
                db.SaveChanges();
                TempData["Notice_Delete_Success"] = true;
            }
            catch (Exception)
            {
                TempData["Notice_Delete_Fail"] = true;
            }
            return RedirectToAction("Index");
        }

        public ActionResult PrintAll()
        {
            var q = new ActionAsPdf("Index");
            return q;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Azure_Assignment/Areas/Admin/Views/Payments/Create.cshtml
@model Azure_Assignment.EF.Payments

@{
    ViewBag.Title = "Create";
}

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Create Sale</h1>
                    <h5 style="color:red">@ViewBag.Error</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                        <li class="breadcrumb-item"><a href="~/Admin/Payments/">Payments</a></li>
                        <li class="breadcrumb-item active">Create Payment</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="card card-green">
                        <div class="card-header">
                            <h3 class="card-title">New Payment</h3>
                        </div>
                        @using (Html.BeginForm("Create", "Payments", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-horizontal">
                                <div class="card-body">
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.PaymentName, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.PaymentName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter payment name" } })
                                            @Html.ValidationMessageFor(model => model.PaymentName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-success">Create</button>
                                    <button type="reset" class="btn btn-default float-right" onclick="window.location = './'">Cancel</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Azure_Assignment/Areas/Admin/Views/Payments/Delete.cshtml
@model Azure_Assignment.EF.Payments

@{
    ViewBag.Title = "Delete";
}

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Delete Payment</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                            <li class="breadcrumb-item"><a href="~/Admin/Payments/">Payments</a></li>
                            <li class="breadcrumb-item active">Delete</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-sm-8">
                            <h1 style="font-weight:bold; font-size:25px" class="card-title">Are you sure you want to delete this?</h1>
                        </div>

                        <div class="col-sm-2">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <div class="card-tools">
                                        <input type="submit" value="Delete" class="btn btn-block btn-secondary float-right btn-danger" />
                                    </div>
                                </div>
                            }
                        </div>

                        <div class="card-tools col-sm-2">
                            <button class="btn btn-block btn-secondary float-right" onclick="window.location.href = '../'">Cancel</button>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-12 col-lg-12 order-12 order-md-12">
                            <div class="row">
                                <div class="col-12">
                                    <div class="post">
                                        <div class="col-sm-2 user-block">
                                            <strong>@Html.DisplayNameFor(model => model.PaymentID)</strong>:
                                        </div>
                                        <p class="col-sm-10">
                                            @Html.DisplayFor(model => model.PaymentID)
                                        </p>
                                    </div>

                                    <div class="post">
                                        <div class="col-sm-2 user-block">
                                            <strong>@Html.DisplayNameFor(model => model.PaymentName)</strong>:
                                        </div>
                                        <p class="col-sm-10">
                                            @Html.DisplayFor(model => model.PaymentName)
                                        </p>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section>
    </div>

Azure_Assignment/Areas/Admin/Views/Payments/Details.cshtml
@model Azure_Assignment.EF.Payments

@{
    ViewBag.Title = "Details";
}

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Payments Detail</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                            <li class="breadcrumb-item"><a href="~/Admin/Payments/">Payments</a></li>
                            <li class="breadcrumb-item active">Detail</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="card">
                <div class="card-header">
                    <h1 style="font-weight:bold; font-size:25px;" class="card-title">Detail of Payment</h1>

                    <div class="card-tools">
                        <button class="btn btn-block btn-secondary float-right" onclick="window.location.href = '../'">Back to List</button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-12 col-lg-12 order-12 order-md-12">
                            <div class="row">
                                <div class="col-12">
                                    <div class="post">
                                        <div class="col-sm-2 user-block">
                                            <strong>@Html.DisplayNameFor(model => model.PaymentID)</strong>:
                                        </div>
                                        <p class="col-sm-10">
                                            @Html.DisplayFor(model => model.PaymentID)
                                        </p>
                                    </div>

                                    <div class="post">
                                        <div class="col-sm-2 user-block">
                                            <strong>@Html.DisplayNameFor(model => model.PaymentName)</strong>:
                                        </div>
                                        <p class="col-sm-10">
                                            @Html.DisplayFor(model => model.PaymentName)
                                        </p>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section>
    </div>

Azure_Assignment/Areas/Admin/Views/Payments/Edit.cshtml
@model Azure_Assignment.EF.Payments

@{
    ViewBag.Title = "Edit";
}

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Payments</h1>
                    <h5 style="color:red">@ViewBag.Error</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                        <li class="breadcrumb-item"><a href="~/Admin/Payments/">Payments</a></li>
                        <li class="breadcrumb-item active">Edit Payments</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Edit Payment</h3>
                        </div>
                        @using (Html.BeginForm("Edit", "Payments", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.PaymentID)
                                <div class="card-body">
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.PaymentName, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                                        <div class="col-sm-10">
                                            @Html.EditorFor(model => model.PaymentName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter sale name" } })
                                            @Html.ValidationMessageFor(model => model.PaymentName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-success">Save</button>
                                    <button type="reset" class="btn btn-default float-right" onclick="window.location = '../'">Cancel</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Azure_Assignment/Areas/Admin/Views/Payments/Index.cshtml
@model IEnumerable<Azure_Assignment.EF.Payments>


<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Manage Payments</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="~/Admin/">Admin</a></li>
                        <li class="breadcrumb-item active">Payments</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Data of Paysments</h3>
                    <p>
                        @Html.ActionLink("Print", "PrintAll")
                    </p>
                    <p>
                        <a class="btn btn-success btn-sm float-right" href="~/Admin/Payments/Create">
                            <i class="fas fa-plus">
                            </i>
                            Create New
                        </a>
                        <a style="cursor:pointer; color:white" id="print" class="btn btn-primary btn-sm float-right"><i class="fas fa-print"></i> Print</a>
                    </p>
                </div>
                <div class="card-body">
                    <table id="tbl_Payments" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.PaymentName)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PaymentName)
                                    </td>

                                    <td class="project-actions text-right">
                                        <a class="btn btn-primary btn-sm" href="~/Admin/Payments/Details/@item.PaymentID">
                                            <i class="fas fa-folder">
                                            </i>
                                            View
                                        </a>
                                        <a class="btn btn-info btn-sm" href="~/Admin/Payments/Edit/@item.PaymentID">
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Edit
                                        </a>
                                        <a class="btn btn-danger btn-sm" href="~/Admin/Payments/Delete/@item.PaymentID">
                                            <i class="fas fa-trash">
                                            </i>
                                            Delete
                                        </a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</div>

@section ScriptConfig
{
    <link href="~/Scripts/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Scripts/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" rel="stylesheet" />
    <script src="~/Scripts/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Scripts/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script>
        $("#tbl_Payments").DataTable({
            "responsive": true,
            "autoWidth": false,
            "aoColumns": [
                null,
                { sWidth: '180px' }
            ]
        });

        $('#print').click(function () {
            window.print();
            return false;
        });

    </script>
}